name: "$(SourceBranchName)+$(BuildID)"

trigger: none #["master"]
pr: none

parameters:
- name: org_type
  displayName: org_type for APIgee (prod/ptl=nonprod)
  type: object
  default:
    ptl:
      nhsd-nonprod:
        - internal-dev
      nhsd-prod:
        - int
    prod:
      nhsd-prod: 
        - prod


stages:
  - stage: build
    jobs:
      - job: build
        displayName: Testing stuff
        timeoutInMinutes: 20
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - bash: echo 'Testing'
            displayName: Testing stuff