name: "$(SourceBranchName)+$(BuildID)"

trigger: none #["master"]
pr: none

parameters:
- name: aws_org
  displayName: aws_org
  type: string
  values:
    - ptl_nhsd_nonprod
    - ptl_nhsd_prod
    - prod_nhsd_prod

# - name: environments
#   displayName: environments
#   type: object
#   default:
#     ptl:
#       nhsd-nonprod:
#         - internal-dev
#         - internal-dev-sandbox
#         - internal-qa
#         - internal-qa-sanbox
#         - ref
#       nhsd-prod:
#         - sandbox
#         - int
#         - dev
#     prod:
#       nhsd-prod: 
#         - prod
- name: ptl_env
  type: object
  default:
    - internal-dev
    - internal-dev-sandbox
    - internal-qa
    - internal-qa-sanbox
    - ref

stages:
  - stage: build
    jobs:
      - job: build
        displayName: Testing stuff
        timeoutInMinutes: 20
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
        - ${{ each env in parameters.ptl_env }}:
          - bash: echo ${{ env }}
            displayName: ${{ env }}
          # - ${{ each env in apigee_org}}:
          #   - bash: echo ${{ env }}
          #     displayName: Testing stuff