name: "$(SourceBranchName)+$(BuildID)"

trigger: none #["master"]
pr: none

parameters:
- name: aws_org
  displayName: aws_org
  type: string
  values:
    - ptl_nhsd_nonprod
    - ptl_nhsd_prod
    - prod

- name: ptl_nhsd_nonprod_envs
  type: object
  default:
    - internal-dev
    - internal-dev-sandbox
    - internal-qa
    - internal-qa-sanbox
    - ref

- name: ptl_nhsd_prod_envs
  type: object
  default:
    - sandbox
    - int
    - dev

- name: prod_envs
  type: object
  default:
    - prod

stages:
  - stage: build
    jobs:
      - job: build
        displayName: Testing stuff
        timeoutInMinutes: 20
        pool:
          vmImage: 'ubuntu-20.04'
        steps:

        - ${{ each env in parameters.{{ parameters.aws_org }}_envs }}:
          - bash: echo ${{ env }}
            displayName: ${{ env }}
          # - ${{ each env in apigee_org}}:
          #   - bash: echo ${{ env }}
          #     displayName: Testing stuff