name: "$(SourceBranchName)+$(BuildID)"

trigger: none #["master"]
pr: none

parameters:
- name: org_type
  displayName: org_type for APIgee (prod/ptl=nonprod)
  type: string
  values:
  - nonprod
  - prod

