name: "$(SourceBranchName)+$(BuildID)"

trigger: none #["master"]
pr: none

parameters:
- name: aws_org
  displayName: aws_org
  type: string
  values:
    - ptl_nhsd_nonprod
    - ptl_nhsd_prod
    - prod_nhsd_prod

- name: environments
  displayName: environments
  type: object
  default:
    ptl:
      nhsd-nonprod:
        - internal-dev
      nhsd-prod:
        - int
    prod:
      nhsd-prod: 
        - prod


stages:
  - stage: build
    jobs:
      - job: build
        displayName: Testing stuff
        timeoutInMinutes: 20
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - bash: echo 'Testing'
            displayName: Testing stuff